"""empty message

Revision ID: ce07796988d2
Revises: 2e81164b1493
Create Date: 2020-05-15 20:24:51.092876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce07796988d2'
down_revision = '2e81164b1493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'generes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('generes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
